CREATE DATABASE IF NOT EXISTS URL;

CREATE TABLE IF NOT EXISTS URL.users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS URL.url_mapping ( 
    id INT AUTO_INCREMENT PRIMARY KEY, 
    long_url TEXT NOT NULL, 
    short_url VARCHAR(10) UNIQUE NOT NULL, 
    clicks INT DEFAULT 0, 
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_id INT,
    FOREIGN KEY (user_id) REFERENCES URL.users(id)
);